data:
  path: /hpc/group/tarokhlab/hy190/data/AL/ALdata/070924_1_cleaned.csv
  window_size: 20
  time_resolution: 3
  sigma: 0.05
  filler: -1
  target: [6]
  batch_size: 8
important_threshold: 1.5
att_encoder:
  lr: 0.00001
  net: 
    rnn: lstm
    num_rnn_layers: 2
    num_rnn_hidden: 4
    attention: True
    embedding_size: 10
    window_size: 20
    context_dense_size: 10
    num_stimuli_condition: 23
    sparse: True
flow_net:
  lr: 0.00001
  net:
    num_blocks: 4
    num_hidden: 64
    num_inputs: Null
    s_act: 'tanh'
    t_act: 'softplus'
    num_cond_inputs: Null
head: 070921
n_runs: 5
n_tries: 1
n_epochs: 200
optimizer:
  name: AdamW
